apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iperf3.fullname" . }}
  labels:
    {{- include "iperf3.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "iperf3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "iperf3.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['-s']
          ports:
            - name: iperf
              containerPort: {{ .Values.service.port }}
              protocol: TCP
