apiVersion: v1
kind: Service
metadata:
  name: {{ include "iperf3.fullname" . }}
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    {{- include "iperf3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  healthCheckNodePort: 30022
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: iperf
  selector:
    {{- include "iperf3.selectorLabels" . | nindent 4 }}
