# Default values for sshjump.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hansenms/gadgetron_ssh_jumpserver
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Secret contained the authorized keys
sshKeySecret: sshkey

service:
  type: LoadBalancer
  port: 22

nodeSelector: {}


