# Default values for iperf3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: networkstatic/iperf3
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5201
  annotations: {}
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"

