apiVersion: v1
kind: Service
metadata:
  name: {{ include "gadgetron.fullname" . }}
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    {{- include "gadgetron.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9002
      protocol: TCP
      name: gadgetron
  selector:
    {{- include "gadgetron.selectorLabels" . | nindent 4 }}
