apiVersion: v1
kind: Service
metadata:
  name: {{ include "stunnel.fullname" . }}
  labels:
    {{- include "stunnel.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.service.dnsPrefix }}
    "service.beta.kubernetes.io/azure-dns-label-name": {{ .Values.service.dnsPrefix | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $conn, $connSettings := .Values.stunnel.connections }}
    - port: {{ $connSettings.listenPort }}
      targetPort: {{ $connSettings.listenPort }}
      name: {{ $conn }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "stunnel.selectorLabels" . | nindent 4 }}
